version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: lifehub-postgres
    environment:
      POSTGRES_DB: lifehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lifehub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lifehub.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 