name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install pnpm
        run: bunx corepack enable && bunx pnpm --version
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm eslint . --fix
      - name: Test
        run: pnpm --filter api test
